{{- if .Values.pvc.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    {{ .Values.pvc.accessModes }}
  storageClassName: {{ .Values.pvc.storageClassName | default "" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "10Gi" }}
{{- end }}
